window.dzsscr_self_options={};
(function(d,a){function c(a,c,R,ha){a[S](B+c,"wheel"==T?R:function(a){!a&&(a=d.event);var B={originalEvent:a,target:a.target||a.srcElement,type:"wheel",deltaMode:"MozMousePixelScroll"==a.type?0:1,deltaX:0,deltaZ:0,preventDefault:function(){a.preventDefault?a.preventDefault():a.returnValue=!1}};"mousewheel"==T?(B.deltaY=-.025*a.wheelDelta,a.wheelDeltaX&&(B.deltaX=-.025*a.wheelDeltaX)):B.deltaY=a.detail;return R(B)},ha||!1)}var B="",S,T;d.addEventListener?S="addEventListener":(S="attachEvent",B="on");
    T="onwheel"in a.createElement("div")?"wheel":void 0!==a.onmousewheel?"mousewheel":"DOMMouseScroll";d.addWheelListener=function(a,d,B){c(a,T,d,B);"DOMMouseScroll"==T&&c(a,"MozMousePixelScroll",d,B)}})(window,document);
(function(d){d.fn.scroller=function(a){if("undefined"==typeof a&&"undefined"!=typeof d(this).attr("data-options")&&""!=d(this).attr("data-options")){var c=d(this).attr("data-options"),c="window.dzsscr_self_options = "+c;eval(c);a=d.extend({},window.dzsscr_self_options);window.dzsscr_self_options=d.extend({},{})}a=d.extend({type:"normal",totalWidth:void 0,totalwidth:void 0,settings_multiplier:3,settings_skin:"skin_default",settings_scrollbar:"on",settings_scrollbyhover:"off",settings_fadeoutonleave:"off",
    settings_replacewheelxwithy:"off",settings_refresh:0,settings_autoheight:"default",settings_autoheight_from_first_item:"off",settings_forcesameheight:"off",settings_fullwidth:"off",settings_hidedefaultsidebars:"off",settings_dragmethod:"drag",settings_autoresizescrollbar:"off",settings_slideshow:"0",scrollBg:"off",force_onlyy:"off",objecter:void 0,secondCon:null,secondCon_tw:null,secondCon_cw:null,secondCon_enable_mouse_scroll:"off",settings_show_sidebar_on_right_side_mouse:"on",enable_easing:"off",
    easing_duration:"1.8",easing_type:"easeInCirc",settings_disableSpecialIosFeatures:"off",touch_leave_native_scrollbar:"off",settings_enable_drag_on_desktops_too:"off",settings_makeFunctional:!1,settings_chrome_multiplier:.1,settings_safari_multiplier:.2,settings_opera_multiplier:.002,settings_ie_multiplier:.08,settings_firefox_multiplier:-1},a);"undefined"==typeof a&&"undefined"!=typeof d(this).attr("data-options")&&""!=d(this).attr("data-options")&&(c=d(this).attr("data-options"),c="var aux_opts = "+
    c,eval(c),a=aux_opts);a.settings_refresh=parseInt(a.settings_refresh,10);a.settings_multiplier=parseFloat(a.settings_multiplier);a.settings_chrome_multiplier=parseFloat(a.settings_chrome_multiplier);a.settings_firefox_multiplier=parseFloat(a.settings_firefox_multiplier);a.settings_slideshow=parseFloat(a.settings_slideshow);Math.linearTween=function(a,d,c,F){return c*a/F+d};Math.easeIn=function(a,d,c,F){return-c*(a/=F)*(a-2)+d};Math.easeOutQuad=function(a,d,c,F){a/=F;return-c*a*(a-2)+d};Math.easeInOutSine=
    function(a,d,c,F){return-c/2*(Math.cos(Math.PI*a/F)-1)+d};Math.easeInCirc=function(a,d,c,F){a/=F;return-c*(Math.sqrt(1-a*a)-1)+d};Math.easeInQuart=function(a,d,c,F){a/=F;return c*a*a*a*a+d};this.each(function(){function B(){qa=!0}function S(){return k}function T(){Ga=!0}function F(){0==qa&&(0<a.settings_slideshow&&(u=null,ja&&(ja=!1,ra="plus"==ra?"minus":"plus"),t="plus"==ra?t+a.settings_slideshow:t-a.settings_slideshow,C()),"on"!=a.enable_easing||is_android()||is_ios()||(w&&(aa=U,ka=la-aa,"easeIn"==
a.easing_type&&(U=Number(Math.easeIn(1,aa,ka,N).toFixed(4))),"easeInCirc"==a.easing_type&&(U=is_safari?Number(Math.easeInCirc(1,aa,ka,N).toFixed(0)):Number(Math.easeInCirc(1,aa,ka,N).toFixed(4))),isNaN(U)&&(U=0),"normal"==a.type&&g.css({top:parseInt(U,10)}),"scrollTop"==a.type&&d(window).scrollTop(-U)),v&&(sa=ma,Ha=ta-sa,ma=Number(Math.easeIn(1,sa,Ha,N).toFixed(4)),"normal"==a.type&&g.css({left:parseInt(ma,10)}),"scrollTop"==a.type&&d(window).scrollTop(-ma))),ua&&ua());if(Ga)return!1;requestAnimFrame(F)}
    function ga(){b.removeClass("scrollbar-active");"on"==a.settings_show_sidebar_on_right_side_mouse&&H>b.offset().left+b.width()-100&&H<=b.offset().left+b.width()&&D>b.offset().top&&D<=b.offset().top+b.height()&&(clearTimeout(O),O=setTimeout(ga,1E3),b.addClass("scrollbar-active"))}function R(e){e.currentTarget==g.get(0)&&(va=!0);a.secondCon&&e.currentTarget==a.secondCon.get(0)&&(wa=!0);ba=g;V=f;W=r;X=h;Y=l;Ia=parseInt(ba.css("left"),10);Ja=parseInt(ba.css("top"),10);"touchstart"==e.type?(xa=e.originalEvent.touches[0].pageX,
        ya=e.originalEvent.touches[0].pageY):(xa=e.pageX,ya=e.pageY);za=!0;a.settings_slideshow=0;if("touchstart"!=e.type)return b.addClass("closedhand"),!1}function ha(a){if(0!=za)return v&&(Ka="touchmove"==a.type?a.originalEvent.touches[0].pageX:a.pageX,x=Ia+(Ka-xa),0<x&&(x/=2),x<-W+V&&(x-=(x+W-V)/2),ba.css("left",x),0<x&&(x=0),x<-W+V&&(x-=x+W-V)),w&&(La="touchmove"==a.type?a.originalEvent.touches[0].pageY:a.pageY,y=Ja+(La-ya),0<y&&(y/=2),y<-Y+X&&(y-=(y+Y-X)/2),ba.css("top",y),0<y&&(y=0),y<-Y+X&&(y-=y+
        Y-X)),"touchmove"!=a.type&&(v&&(c=x/-(W-V),Fa(c)),w&&(a=c=y/-(Y-X),k=a*-(l-h),E=a*(l-I),C())),!1}function ia(a){za=wa=va=!1;b.removeClass("closedhand")}function Fa(e,b){var c={secondCon_targetX:""},c=d.extend(c,b);u=e*-(r-f);t=e*(f-z);null!=a.secondCon&&(A=e*-(L-J));""!=c.secondCon_targetX&&(A=c.secondCon_targetX);C()}function Wa(e){1<e&&(e/=r-f);u=e*-(r-f);t=e*(f-z);null!=a.secondCon&&(A=e*-(L-J));C()}function Xa(a,Ma){var c={show_scrollbar:!0};Ma&&(c=d.extend(c,Ma));1<a&&(a/=l-h);k=a*-(l-h);E=a*
        (h-I);C(c);c.show_scrollbar&&(clearTimeout(O),O=setTimeout(ga,1E3),b.addClass("scrollbar-active"))}function Z(){d(window).width();P=d(window).height();if(1==a.settings_makeFunctional){var e=!1,c=document.URL,m=c.indexOf("://")+3,p=c.indexOf("/",m),c=c.substring(m,p);-1<c.indexOf("a")&&-1<c.indexOf("c")&&-1<c.indexOf("o")&&-1<c.indexOf("l")&&(e=!0);-1<c.indexOf("o")&&-1<c.indexOf("z")&&-1<c.indexOf("e")&&-1<c.indexOf("h")&&-1<c.indexOf("t")&&(e=!0);-1<c.indexOf("e")&&-1<c.indexOf("v")&&-1<c.indexOf("n")&&
    -1<c.indexOf("a")&&-1<c.indexOf("t")&&(e=!0);if(0==e)return}f=void 0!=a.totalWidth?a.totalWidth:b.outerWidth(!1);void 0!=a.totalHeight&&0!=a.totalHeight?h=a.totalHeight:0!=b.height()&&(h=b.outerHeight(!1));"on"==a.settings_autoheight_from_first_item&&(h=g.children().children().eq(0).height());"scrollTop"==a.type&&(h=d(window).height(),l=b.outerHeight(),99<Math.abs(l-Aa)&&(k=E/-(P-I)*(l-P),l<Aa&&(l<P?E=k=0:Q())),Aa=l);null!=a.secondCon&&(null==a.secondCon_tw&&(J=f),null==a.secondCon_cw&&(L=a.secondCon.width()));
        is_ie()&&7==version_ie()&&b.css("overflow","visible");"on"==a.settings_hidedefaultsidebars&&(b.css("overflow","hidden"),d("html").css("overflow","hidden"));g&&(r=g.width(),l=g.outerHeight(),0<g.find(".real-inner").length&&(r=g.find(".real-inner").outerWidth(),l=g.find(".real-inner").outerHeight(),g.css({width:r}),Na&&g.height(l),g.css({})));g&&na&&b.height(g.height());g&&g.hasClass("calculate-inner");"scrollTop"==a.type&&b.css("position");"on"==a.settings_forcesameheight&&(h=l);"on"==a.scrollBg&&
        (l=b.height(),h=d(window).height());w=l<=h?!1:!0;r<=f?v=!1:(v=!0,b.addClass("dir-hor"));"on"==a.force_onlyy&&(v=!1);"on"==a.force_onlyx&&(w=!1);"scrollTop"==a.type&&(w=!0,l<=h&&(w=!1));1==v?b.addClass("dir-hor"):b.removeClass("dir-hor");1==w?b.addClass("dir-ver"):b.removeClass("dir-ver");0==v&&void 0!=n&&(n.remove(),K.remove(),K=n=void 0);0==w&&void 0!=q&&(q.remove(),M.remove(),M=q=void 0);0==w&&0==v?b.addClass("no-need-for-nav"):(b.removeClass("no-need-for-nav"),"on"==a.settings_scrollbar&&(void 0==
        q&&w&&(G.append('<div class="scrollbary_bg"></div>'),G.append('<div class="scrollbary"></div>')),void 0==n&&v&&(G.append('<div class="scrollbarx_bg"></div>'),G.append('<div class="scrollbarx"></div>'))),void 0==q&&w&&(q=G.children(".scrollbary"),M=G.children(".scrollbary_bg"),I=q.height(),"on"==a.settings_autoresizescrollbar&&(e=h/l*h,q.css("height",e),I=e),M.css("height",h),"on"==a.settings_fadeoutonleave&&(q.css("opacity",0),M.css("opacity",0)),M.mousedown(function(e){oa=!0;a.settings_slideshow=
            0;ca=D-q.offset().top+b.offset().top;"scrollTop"==a.type&&(ca=D-q.offset().top+d(window).scrollTop());return!1}),q.mousedown(function(e){oa=!0;a.settings_slideshow=0;ca=D-q.offset().top+b.offset().top;"scrollTop"==a.type&&(ca=D-q.offset().top+d(window).scrollTop());return!1})),void 0==n&&v&&(n=G.children(".scrollbarx"),K=G.children(".scrollbarx_bg"),z=n.width(),"on"==a.settings_autoresizescrollbar&&(e=f/r*f,n.css("width",e),z=e),K.css("width",f),"on"==a.settings_fadeoutonleave&&(n.css("opacity",0),
            K.css("opacity",0)),r<=f&&"on"==a.settings_fullwidth&&(n.hide(),K.hide()),n.mousedown(function(e){pa=!0;a.settings_slideshow=0;Oa=H-n.offset().left+b.offset().left;return!1}),K.mousedown(function(e){pa=!0;a.settings_slideshow=0;return!1})),n&&1==v&&(parseInt(n.css("left")),"on"==a.settings_autoresizescrollbar&&(e=f/r*f,n.css("width",e),z=e)),q&&1==w&&(parseInt(q.css("top")),"on"==a.settings_autoresizescrollbar&&(e=h/l*h,q.css("height",e),I=e)),n&&1==v&&K.css("width",f),n&&v&&f>r&&"block"==n.css("display")&&
        (K.hide(),n.hide()),n&&v&&f<r&&"none"==n.css("display")&&(K.show(),n.show()),q&&1==w&&M.css("height",h),C({do_not_clear_suspend_enter_frame:"on"}))}function Ya(){E=k=0;C()}function Ba(){d(window).width();P=d(window).height();Z()}function Q(e){var c=d(this);"scrollTop"==a.type&&(c=b);if(!Ca){da=ea=!1;(e=e||window.event)&&e.target&&b.has(d(e.target));m=Pa(e);p=Qa(e);m*=a.settings_multiplier;p*=a.settings_multiplier;Za&&(m*=a.settings_chrome_multiplier,p*=a.settings_chrome_multiplier);$a&&(m=Pa(e),p=
        Qa(e),m*=a.settings_safari_multiplier,p*=a.settings_safari_multiplier);is_firefox()&&(m*=a.settings_firefox_multiplier,p*=a.settings_firefox_multiplier);is_opera()&&(m*=a.settings_opera_multiplier,p*=a.settings_opera_multiplier);is_ie()&&(m=0,p=Ra(e),m*=a.settings_ie_multiplier,p*=a.settings_ie_multiplier);11<=getInternetExplorerVersion()&&(m=0,p=Ra(e),m*=a.settings_ie_multiplier,p*=a.settings_ie_multiplier);"on"==a.settings_replacewheelxwithy&&0==m&&(m=p);if(b.get(0)==c.get(0)||a.secondCon&&a.secondCon.get(0)==
        c.get(0))if(w&&(k+=p*a.settings_multiplier,E=k/(l-h)*-(h-I)),v&&(u+=m*a.settings_multiplier,t=u/(r-f)*-(f-z),null!=a.secondCon)){if(void 0==A||isNaN(A))A=0;A+=L/r*a.settings_multiplier*m}C();0==v&&(ea=!0);0==w&&(da=!0);if(0!=p&&0==da)if(0==is_ie8())e.stopPropagation(),e.preventDefault();else return!1;if(0!=m&&0==ea)if(0==is_ie8())e.stopPropagation(),e.preventDefault();else return!1;if(0!=m||0!=p)clearTimeout(O),O=setTimeout(ga,1E3),b.addClass("scrollbar-active");if(a.type="scrollTop",is_safari())return!1}}
    function Ra(a){if(!a)return 0;if(a.originalEvent&&a.originalEvent.wheelDelta)return a.originalEvent.wheelDelta;if(a.wheelDelta)return a.wheelDelta;if(a.detail)return a.detail;if(void 0!=a.originalEvent&&void 0!=a.originalEvent.detail)return-40*a.originalEvent.detail}function Pa(a){if(!a)return 0;if(is_firefox())return 1==a.axis?a.detail:0;if(a.originalEvent&&a.originalEvent.wheelDeltaX)return a.originalEvent.wheelDeltaX;if(a.wheelDelta)return a.wheelDeltaX;if(void 0!=a.originalEvent&&a.originalEvent.detail)return-40*
        a.originalEvent.detail}function Qa(a){if(!a)return 0;if(is_firefox())return 2==a.axis?a.detail:0;if(a.originalEvent&&a.originalEvent.wheelDeltaY)return a.originalEvent.wheelDeltaY;if(a.wheelDelta)return a.wheelDeltaY;if(void 0!=a.originalEvent&&a.originalEvent.detail)return-40*a.originalEvent.detail}function C(e){var c={animate_inner:"on",animate_sc:"on",force_no_easing:"off",do_not_clear_suspend_enter_frame:"off"},c=d.extend(c,e);w&&(0<k&&(k=0),"scrollTop"==a.type&&(h=P),k<-(l-h)&&(k=-(l-h)),isNaN(k)&&
    (k=0),0>E&&(E=0,da=!0),E>h-I&&(E=h-I,da=!0),q&&(b.hasClass("easing"),"normal"==a.type&&("on"!=a.enable_easing?g.css({top:k}):la=k),"scrollTop"==a.type&&("on"!=a.enable_easing||"on"==c.force_no_easing?(d(window).scrollTop(-k),Sa=N,N=0,la=k,setTimeout(function(){N=Sa},100)):la=k),q.css({top:E}),"on"==a.scrollBg&&b.css("background-position","center "+k+"px")));v&&(null==u&&(u=t/(f-z)*(f-r)),u<-(r-f)&&(u=-(r-f)),0<u&&(u=0),null!=a.secondCon&&(A<-(L-J)&&(A=-(L-J)),0<A&&(A=0)),0>t&&(t=0,ja=ea=!0),t>f-z&&
    (t=f-z,ja=ea=!0),n&&(b.hasClass("easing"),"normal"==a.type&&("on"!=a.enable_easing?g.css({left:u}):ta=u),"scrollTop"==a.type&&("on"!=a.enable_easing?d(window).scrollLeft(-u):ta=u),a.secondCon&&a.secondCon.css({left:A}),n.css({left:t}),"on"==a.scrollBg&&b.css("background-position",""+k+"px center")));"off"==c.do_not_clear_suspend_enter_frame&&(qa=!1,clearTimeout(Ta),Ta=setTimeout(B,1E3))}function ab(){var c=0,d=0,k=0,m=0;g&&(c=g.width()-b.width(),d=g.position().left,k=g.height()-b.height(),m=g.position().top);
        var l=null,n=null;if(a.secondCon){var l=a.secondCon,n=l.parent(),p=l.width()-n.width(),q=l.position().left;l.height();n.height();l.position()}Ua&&b[0]==document.getElementById("scrollc3")&&(Ua=!1);va&&(t=-d/c*(f-z),E=-m/k*(h-z),c={animate_inner:"off"},l&&(A=-(t/(J-z)*(L-J))),C(c));wa&&(t=-q/p*(f-z),u=t/f*(f-r),c={animate_sc:"off"},C(c))}var f=0,h=0,r=0,l=0,Aa=0,P=0,fa=null,G=null,g=null,Na=!1,na=!1,m=0,p=0,E=0,t=0,va=!1,wa=!1,q=void 0,M=void 0,n=void 0,K=void 0,b=d(this),H=0,D=0,oa=!1,pa=!1,Ca=!1,
        I=0,z=0,Oa=0,ca=0,u=0,k=0,J,L,A,Da,ea=!1,da=!1,v=!0,w=!0,Va=0,O,ua=null,ba,V=0,X=0,W=0,Y=0,Ia=0,Ja=0,x=0,y=0,xa,ya,Ka,La,za=!1,Ua=!0,ja=!1,ra="plus",Ga=!1,qa=!1,Ta,N=1.8,U=0,ma=0,aa=0,sa=0,la=0,ta=0,ka=0,Ha=0,Sa=0,Ea=!1,Za=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),$a=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);if(b.hasClass("dzsscr-inited"))return!1;(function(){f=void 0==a.totalWidth?b.width():a.totalWidth;h=void 0==a.totalHeight?b.height():
        a.totalHeight;N=parseFloat(a.easing_duration);"normal"==a.type&&(g=b.find(".inner").eq(0));var c=String(b.attr("class"));-1==c.indexOf("skin_")&&b.addClass(a.settings_skin);c=String(b.attr("class"));(c=/(skin_.*?) /.exec(c))&&c[1]&&(a.settings_skin=c[1]);"normal"==a.type&&(0==g.parent().hasClass("scroller")&&g.wrap('<div class="scroller"></div>'),fa=b.find(".scroller").eq(0));if(is_touch_device()&&"on"!=a.settings_disableSpecialIosFeatures){if("scrollTop"==a.type)return!1;fa&&fa.css("overflow","auto");
        if("on"==a.touch_leave_native_scrollbar)return!1;a.secondCon&&a.secondCon.parent().css("overflow","auto");b.addClass("is-touch")}"scrollTop"==a.type&&(b.addClass("scroller-con type-scrollTop"),d("html").css("overflow-y","hidden"),setTimeout(function(){},1E3),d(document).delegate("a[href^=#]","click",function(){var a=d(this);0<d(a.attr("href")).length&&d(".scroller-con.type-scrollTop").get(0)&&d(".scroller-con.type-scrollTop").get(0).api_scrolly_to&&(a=d(a.attr("href")).offset().top-100,d(".scroller-con.type-scrollTop").get(0).api_scrolly_to(a));
        return!1}),b.bind("mousedown",function(a){Ea=2==a.which?Ea?!1:!0:!1}),b.bind("mousemove",function(a){Ea&&(k=-(a.clientY/P*(b.height()-P)),C())}),d("body").bind("keydown",function(a){38==a.keyCode&&(k+=30,C());40==a.keyCode&&(k-=30,C())}));Da=b;Da.append('<div class="scrollbar"></div>');G=Da.children(".scrollbar").eq(0);is_touch_device()&&G.addClass("easing");!g||""!=g.get(0).style.height&&"auto"!=g.get(0).style.height||(Na=!0);"auto"!=a.settings_autoheight||""!=b.get(0).style.height&&"auto"!=b.get(0).style.height||
    (na=!0);"on"==a.settings_autoheight&&(na=!0);"off"==a.settings_autoheight&&(na=!1);Z();0==b.css("opacity")&&(b.animate({opacity:1},600),b.parent().children(".preloader").fadeOut("slow"));0==Va&&(Va=r+50);b.hasClass("is-touch")&&"off"==a.settings_disableSpecialIosFeatures&&fa&&fa.css({overflow:"auto"});void 0!=b.get(0)&&(b.get(0).reinit=Ba,b.get(0).api_destroy=T,b.get(0).scrollToTop=Ya,b.get(0).updateX=Fa,b.get(0).fn_scrollx_to=Wa,b.get(0).api_scrolly_to=Xa,b.get(0).api_toggle_resize=Z,b.get(0).api_get_view_index_y=
        S,b.get(0).api_set_action_handle_frame=function(a){ua=a},b.get(0).api_block_scroll=function(a){Ca=!0},b.get(0).api_unblock_scroll=function(a){Ca=!1});0<a.settings_refresh&&setInterval(Ba,a.settings_refresh);"0"==b.find(".scrollbar").css("opacity")&&b.find(".scrollbar").animate({opacity:1},600);d(window).bind("resize",Z);Z();setTimeout(Z,1E3);F();b.addClass("dzsscr-inited")})();b.get(0).api_reinit=Ba;b.get(0).api_handle_wheel=Q;"on"==a.settings_scrollbyhover||0!=b.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures||
    ("scrollTop"==a.type?(d(window)[0].addEventListener&&d(window)[0].addEventListener("DOMMouseScroll",Q,!1),d(window)[0].onmousewheel=Q):(b[0].addEventListener&&b[0].addEventListener("DOMMouseScroll",Q,!1),b[0].onmousewheel=Q),a.secondCon&&(a.secondCon[0].addEventListener&&a.secondCon[0].addEventListener("DOMMouseScroll",Q,!1),a.secondCon[0].onmousewheel=Q));0!=b.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures||d(document).mousemove(function(c){H=c.pageX-b.offset().left;D=c.pageY-b.offset().top;
        "scrollTop"==a.type&&(D=c.pageY-d(window).scrollTop());"on"==a.settings_scrollbyhover&&(0>H||0>D||H>f+20||D>h+20)||(1!=w||1!=oa&&"on"!=a.settings_scrollbyhover||(G.addClass("dragging"),"normal"==a.settings_dragmethod&&(E=D/h*(h-I),k=D/h*(h-l)),"drag"==a.settings_dragmethod&&(E=0+(D-0)-ca,k=E/-(h-I)*(l-h)),k=parseInt(k,10),C()),1!=v||1!=pa&&"on"!=a.settings_scrollbyhover||(G.addClass("dragging"),"normal"==a.settings_dragmethod&&(t=H/f*(f-z),u=H/f*(f-r),null!=a.secondCon&&(A=H/J*(J-L))),"drag"==a.settings_dragmethod&&
        (t=0+(H-0)-Oa,u=t/-(f-z)*(r-f),null!=a.secondCon&&(A=t/-(J-z)*(L-J))),C()),"on"==a.settings_fadeoutonleave&&(q.animate({opacity:1},{queue:!1,duration:500}),M.animate({opacity:1},{queue:!1,duration:500})),"on"==a.settings_show_sidebar_on_right_side_mouse&&H>b.offset().left+b.width()-100&&H<=b.offset().left+b.width()&&D>b.offset().top&&D<=b.offset().top+b.height()&&(clearTimeout(O),O=setTimeout(ga,1E3),b.addClass("scrollbar-active")))});"on"==a.settings_enable_drag_on_desktops_too&&(b.addClass("swipe-enabled"),
    g&&(g.bind("mousedown",R),d(document).bind("mousemove",ha),d(document).bind("mouseup",ia)),a.secondCon&&(a.secondCon.bind("touchstart",R),a.secondCon.bind("touchend",ia)));0==b.hasClass("is-touch")||"on"==a.settings_disableSpecialIosFeatures?d(document).mouseup(function(a){pa=oa=!1;G&&G.removeClass("dragging")}):(b.addClass("swipe-enabled"),g&&(g.bind("touchstart",R),g.bind("touchmove",ha),g.bind("touchend",ia)),a.secondCon&&(a.secondCon.bind("touchstart",R),a.secondCon.bind("touchend",ia)));"on"!=
    a.settings_fadeoutonleave||0!=is_ios()&&"on"!=a.settings_disableSpecialIosFeatures||b.mouseleave(function(a){q.animate({opacity:0},{queue:!1,duration:500});M.animate({opacity:0},{queue:!1,duration:500})});b.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures&&setInterval(ab,80);return this})};window.dzsscr_init=function(a,c){if("undefined"!=typeof c&&"undefined"!=typeof c.init_each&&1==c.init_each){var B=0,S;for(S in c)B++;1==B&&(c=void 0);d(a).each(function(){d(this).scroller(c)})}else d(a).scroller(c)}})(jQuery);
function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_android(){return-1!=navigator.platform.indexOf("Android")}function is_touch_device(){return!!("ontouchstart"in window)}function is_ie(){return-1!=navigator.appVersion.indexOf("MSIE")?!0:!1}function is_firefox(){return-1!=navigator.userAgent.indexOf("Firefox")?!0:!1}function is_opera(){return-1!=navigator.userAgent.indexOf("Opera")?!0:!1}
function is_chrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function is_safari(){return/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor)}function version_ie(){return parseFloat(navigator.appVersion.split("MSIE")[1])}function version_firefox(){if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}function version_opera(){if(/Opera[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}
function is_ie8(){return is_ie()&&9>version_ie()?!0:!1}function is_ie9(){return is_ie()&&9==version_ie()?!0:!1}function getInternetExplorerVersion(){var d=-1;if("Microsoft Internet Explorer"==navigator.appName){var a=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=c.exec(a)&&(d=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(a=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=c.exec(a)&&(d=parseFloat(RegExp.$1)));return d}
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(d){window.setTimeout(d,1E3/60)}}();jQuery(document).ready(function(d){dzsscr_init(".scroller-con.auto-init",{init_each:!0})});jQuery(window).load(function(){dzsscr_init(".scroller-con.auto-init-onload",{init_each:!0})});