window.dzszfl_self_options={};Math.easeIn=function(d,b,a,l){return-a*(d/=l)*(d-2)+b};function sory_by_sort(d,b){var a=0,l=0,a=Number(jQuery(d).attr("data-sort")),l=Number(jQuery(b).attr("data-sort"));return a<l?-1:a>l?1:0}
window.dzs_check_lazyloading_images=function(){var d=jQuery(window).scrollTop(),b=jQuery(window).height();jQuery("img[data-src]").each(function(){var a=jQuery(this);if(a.offset().top<=d+b){var l=new Image;l.onload=function(){if(a.attr("data-src")){var b=a.attr("data-src");a.attr("src",b);a.attr("data-src","");a.addClass("loaded")}a.hasClass("set-height-auto-after-load")&&a.css("height","auto");a.parent().parent().parent().parent().parent().hasClass("mode-isotope")&&(b=a.parent().parent().parent().parent().parent(),
b.get(0)&&b.get(0).api_relayout_isotope&&b.get(0).api_relayout_isotope())};l.src=a.attr("data-src")}})};window.dzs_check_lazyloading_images_inited||(window.dzs_check_lazyloading_images_inited=!1);
(function(d){d.fn.prependOnce=function(b,a){var l=d(this);if("undefined"==typeof a){var r=/class="(.*?)"/.exec(b);"undefined"!=typeof r[1]&&(a="."+r[1])}return 1>l.children(a).length?(l.prepend(b),!0):!1};d.fn.appendOnce=function(b,a){var l=d(this);if("undefined"==typeof a){var r=/class="(.*?)"/.exec(b);"undefined"!=typeof r[1]&&(a="."+r[1])}return 1>l.children(a).length?(l.append(b),!0):!1};d.fn.zfolio=function(b){if("undefined"==typeof b&&"undefined"!=typeof d(this).attr("data-options")&&""!=d(this).attr("data-options")){var a=
    d(this).attr("data-options");eval(" window.dzszfl_self_options = "+a);b=d.extend({},window.dzszfl_self_options);window.dzszfl_self_options=d.extend({},{})}b=d.extend({design_item_thumb_just_use_img:"off",settings_autoHeight:"on",settings_skin:"skin-default",settings_mode:"isotope",settings_disableCats:"off",settings_clickaction:"none",title:"",design_total_height_full:"off",design_item_width:"0",design_item_height:"0",design_item_height_same_as_width:"off",design_sizecontain_forfeatureimage:"off",
    design_thumbw:"",design_item_thumb_height:"",design_categories_pos:"top",design_categories_align:"auto",design_specialgrid_chooser_align:"auto",design_pageContent_pos:"top",design_categories_style:"normal",design_waitalittleforallloaded:"off",use_scroll_lazyloading_for_images:"off",settings_ajax_enabled:"off",settings_ajax_loadmoremethod:"scroll",settings_ajax_pages:[],settings_lightboxlibrary:"zoombox",item_inner_addid:"",settings_preloadall:"off",settings_add_loaded_on_images:"off",settings_useLinksForCategories:"off",
    settings_useLinksForCategories_enableHistoryApi:"off",disable_itemmeta:"off",disable_cats:"off",wall_settings:{},settings_enableHistory:"off",audioplayer_swflocation:"ap.swf",videoplayer_swflocation:"preview.swf",settings_makeFunctional:!0,settings_defaultCat:"",settings_forceCats:[],settings_categories_strall:"All",settings_categories_strselectcategory:"Select Category",settings_mode_masonry_layout:"masonry",settings_mode_masonry_column_width:1,settings_set_forced_width:"off",settings_isotope_settings:{getSortData:{number:function(b){return parseInt(d(b).attr("data-sort"),
        10)}},itemSelector:".isotope-item",sortBy:"number",layoutMode:"packery",masonry:{columnWidth:".grid-sizer"},packery:{columnWidth:1}},zoombox_settings:{},settings_mode_masonry_layout_straightacross_setitemsoncenter:"off",item_extra_class:"",excerpt_con_transition:"zoom",excerpt_con_resize_videos:"off",excerpt_con_responsive_ratio:"810",outer_con_selector_con:null},b);this.each(function(){function a(){var E=1;v=k=0;g.children(".zfolio-item:not(.inited)").each(function(){var e=d(this);e.children().eq(0).hasClass("zfolio-item--inner")?
"cols"==b.settings_mode&&e.children(".zfolio-item--inner").hasClass("zoombox")&&e.children(".zfolio-item--inner").attr("data-zoombox-sort",E-1):e.attr("data-link")&&"skin-melbourne"==b.design_skin?e.wrapInner('<a href="'+e.attr("data-link")+'" class="zfolio-item--inner"></a>'):e.wrapInner('<div class="zfolio-item--inner"></div>');var n=e.children(".zfolio-item--inner");if(b.item_inner_addid){var f="";c.attr("id")&&(f+=c.attr("id")+"-");(f+=b.item_inner_addid+String(E))&&n.attr("id",f)}n.prependOnce('<div class="the-feature-con"></div>');
    "on"==b.design_item_thumb_just_use_img?(f='<img class="the-feature',"on"==b.use_scroll_lazyloading_for_images?(f+=' lazyloading-transition-fade set-height-auto-after-load" data-src="'+e.attr("data-thumbnail")+'"',f+='" style="height:300px; display:block;"'):f+='" src="'+e.attr("data-thumbnail")+'"',f+="/>",n.find(".the-feature-con").eq(0).prependOnce(f),n.find(".the-feature-con").eq(0).addClass("auto-height")):n.find(".the-feature-con").eq(0).prependOnce('<div class="the-feature" style="background-image: url('+
        e.attr("data-thumbnail")+');"></div>');var a="";e.attr("data-overlay_extra_class")&&(a+=" "+e.attr("data-overlay_extra_class"));var h=!1,f='<div class="the-overlay'+a+'" ';if(e.attr("data-link")){if("skin-silver"==b.design_skin||"skin-qcre"==b.design_skin)f='<a href="'+e.attr("data-link")+'" class="the-overlay '+a+'" ',h=!0;"skin-gazelia"==b.design_skin&&(h=!1,f='<div class="the-overlay" >'+('<a href="'+e.attr("data-link")+'" class="the-overlay-anchor '+a+'"'),e.attr("data-overlay_anchor_extra_attr")&&
    (f+=e.attr("data-overlay_anchor_extra_attr")),f+=">",0<e.children(".overlay-anchor-extra-html").length&&(f+=e.children(".overlay-anchor-extra-html").eq(0).html()),f+="</a")}e.attr("data-overlay_extra_attr")&&(f+=e.attr("data-overlay_extra_attr"));f+=">";f=h?f+"</a>":f+"</div>";n.find(".the-feature-con").eq(0).appendOnce(f);"skin-gazelia"==b.design_skin&&0<e.children(".the-overlay-anchor").length&&e.find(".the-overlay").eq(0).append(e.children(".the-overlay-anchor").eq(0));0==F&&0<y&&n.find(".the-feature-con").height(y);
    e.addClass(b.item_extra_class);e.addClass("inited");e.attr("data-sort",10*E);n=e.attr("data-category");if(void 0!=n&&""!=n)for(n=n.split(";"),f=0;f<n.length;f++){h=n[f];a=n[f];void 0!=h&&(h=h.replace(/ /gi,"-"),e.addClass("cat-"+h));M=!1;for(h=0;h<z.length;h++)z[h]==a&&(M=!0);0==M&&z.push(a)}E++;if("cols"==b.settings_mode){if(c.hasClass("layout-2-cols-10-margin")||c.hasClass("layout-2-cols-15-margin"))2<=k&&(k=0),u=2;if(c.hasClass("layout-3-cols-10-margin")||c.hasClass("layout-3-cols-15-margin"))3<=
    k&&(k=0),u=3;if(c.hasClass("layout-4-cols-10-margin")||c.hasClass("layout-4-cols-15-margin"))4<=k&&(k=0),u=4;if(c.hasClass("layout-5-cols-10-margin")||c.hasClass("layout-5-cols-15-margin"))5<=k&&(k=0),u=5;g.children(".dzs-col").eq(k).append(e);k++}})}function r(){if("isotope"==b.settings_mode&&(g.children("*:not(.grid-sizer)").addClass("isotope-item"),(c.hasClass("layout-5-cols-15-margin")||c.hasClass("layout-5-cols-10-margin"))&&g.prepend('<div class="grid-sizer"></div>'),"isotope"==b.settings_mode)){var a=
{},a=d.extend(a,b.settings_isotope_settings);a.transitionDuration="0s";g.isotope(a);setTimeout(function(){a.transitionDuration="0.3s";g.isotope(a);c.addClass("dzszfl-ready-for-transitions")},2E3)}G=g.children();if(1<z.length&&0==c.find(".selector-con").length){var e;e='<div class="selector-con"><div class="categories"></div></div>';b.outer_con_selector_con?t=b.outer_con_selector_con:(g.before(e),t=c.find(".selector-con").eq(0));w=t.children(".categories");"on"==b.settings_useLinksForCategories?w.append('<a class="a-category allspark active" href="'+
    add_query_arg(window.location.href,"dzsp_defCategory_"+x,0)+'">'+b.settings_categories_strall+"</a>"):w.append('<div class="a-category allspark active">'+b.settings_categories_strall+"</div>");for(m=0;m<z.length;m++)w.append(""),"on"==b.settings_useLinksForCategories?w.append('<a class="a-category" href="'+add_query_arg(window.location.href,"dzsp_defCategory_"+x,m+1)+'">'+z[m]+"</a>"):w.append('<div class="a-category">'+z[m]+"</div>");t.removeClass("empty-categories")}else b.outer_con_selector_con&&
(t=b.outer_con_selector_con,t.addClass("empty-categories"));c.find(".content-opener").unbind("click");c.find(".content-opener").bind("click",Z);t&&(t.undelegate(".a-category","click"),t.delegate(".a-category","click",aa));c.get(0).api_destroy=ba;c.get(0).api_handle_resize=D;c.get(0).api_destroy_listeners=ca;c.get(0).api_relayout_isotope=function(){S&&(clearTimeout(T),T=setTimeout(da,500))};0==window.dzs_check_lazyloading_images_inited?(window.dzs_check_lazyloading_images_inited=!0,d(window).bind("scroll",
    window.dzs_check_lazyloading_images),window.dzs_check_lazyloading_images(),setTimeout(function(){window.dzs_check_lazyloading_images()},1500),setTimeout(function(){window.dzs_check_lazyloading_images()},2500)):window.dzs_check_lazyloading_images&&(window.dzs_check_lazyloading_images(),setTimeout(function(){window.dzs_check_lazyloading_images&&window.dzs_check_lazyloading_images()},1E3),setTimeout(function(){window.dzs_check_lazyloading_images&&window.dzs_check_lazyloading_images()},2E3),setTimeout(function(){window.dzs_check_lazyloading_images&&
window.dzs_check_lazyloading_images()},3E3));setTimeout(function(){S=!0},2500);D();d(window).bind("resize",D);"on"==b.settings_add_loaded_on_images&&(U(),setTimeout(function(){V({force_all_loaded:!0})},6700));setTimeout(function(){H()},1200)}function H(){"0"==g.css("opacity")&&g.animate({opacity:1},{duration:500,queue:!1});c.addClass("dzszfl-ready")}function U(){var b=G.eq(A),c=new Image;c.src=b.attr("data-thumbnail");c.onload=W}function W(b,c){var n=b.target,a={};c&&d.extend(a,c);this&&this.removeEventListener&&
this.removeEventListener("load",W);G.eq(A).addClass("image-loaded");parseInt(n.naturalWidth,10);parseInt(n.naturalHeight,10);A++;V()}function V(a){var e={force_all_loaded:!1};a&&(e=d.extend(e,a));e.force_all_loaded&&(A=I,G.addClass("image-loaded"));"on"==b.settings_preloadall&&A>=I&&setTimeout(H,1E3);"on"==b.settings_add_loaded_on_images&&A>=I&&c.addClass("all-images-loaded");A<I&&U()}function ca(){c.find(".content-opener").unbind("click");d(window).unbind("resize",D);J=!0}function ba(){J=!0}function aa(c){var a=
    d(this);if("click"==c.type&&a.hasClass("a-category")){if(a.hasClass("active"))return t.toggleClass("is-opened"),!1;c=a.parent().children().index(a);a=a.html();t.removeClass("is-opened");"on"==b.settings_useLinksForCategories&&"on"==b.settings_useLinksForCategories_enableHistoryApi&&history.pushState({foo:"bar"},"ZoomFolio Category "+c,add_query_arg(window.location.href,"dzsp_defCategory_"+x,c));if("on"!=b.settings_useLinksForCategories||"on"==b.settings_useLinksForCategories_enableHistoryApi)return ea(a),
    !1}}function D(a,e){var n={calculate_dims_init:!0,calculate_excerpt_con:!0,excerpt_con_noanimation:!0};e&&(n=d.extend(n,e));X=d(window).width();d(window).height();K=c.width();520>=K?c.addClass("under-520"):c.removeClass("under-520");720>=K?(c.addClass("under-720"),b.outer_con_selector_con&&b.outer_con_selector_con.addClass("under-720")):(c.removeClass("under-720"),b.outer_con_selector_con&&b.outer_con_selector_con.removeClass("under-720"));1E3>=K?(c.addClass("under-1000"),b.outer_con_selector_con&&
b.outer_con_selector_con.addClass("under-1000")):(c.removeClass("under-1000"),b.outer_con_selector_con&&b.outer_con_selector_con.removeClass("under-1000"));if(n.calculate_excerpt_con){if(p&&"on"==b.excerpt_con_resize_videos&&h&&0<h.find(".vplayer").length){var f=h.find(".vplayer").eq(0),g=Number(b.excerpt_con_responsive_ratio),k=h.width();f.parent().hasClass("dzs-col-8")&&(g*=2/3,810==b.excerpt_con_responsive_ratio&&(k=g=580,1E3>=X&&(k=h.width())));var l=0;f.data("initial-height-for-excerpt-content")?
    l=Number(f.data("initial-height-for-excerpt-content")):(l=f.height(),f.data("initial-height-for-excerpt-content",l));f.height(l/g*k)}setTimeout(function(){if(p){B.css({padding:h.css("padding-top"),width:c.outerWidth()});var d=0;"zoom"==b.excerpt_con_transition?(q.css({}),h.css({height:B.outerHeight()})):(B.outerHeight(),n.excerpt_con_noanimation&&(d=h.children(".dzs-colcontainer").outerHeight(),h.css({height:d}),d=Number(p.attr("data-sort")),0<d&&q.attr("data-sort",d+1),q.css({height:""})))}},500)}n.calculate_dims_init&&
(N&&clearTimeout(N),N=setTimeout(Y,500))}function Y(a){var e={parse_items:!0,relayout_isotope:!0,disable_easing_on_isotope_transiton:!1};a&&(e=d.extend(e,a));e.parse_items&&(v=k=0,L=g.children(".zfolio-item"),"cols"==b.settings_mode&&(L=g.find(".dzs-col > .zfolio-item"),L.sort(sory_by_sort)),L.each(function(){var a=d(this),f=-1;if(c.hasClass("layout-5-cols-15-margin")||c.hasClass("layout-5-cols-10-margin")){var e=c.width();"-1px"==g.css("margin-left")&&(e+=2,g.css("width","calc(100% + 6px)"));"-15px"==
g.css("margin-left")&&(e+=30,g.css("width","calc(100% + 36px)"));f=parseInt(e/5,10);c.hasClass("layout-5-cols-10-margin")&&c.hasClass("under-1000")&&(f=parseInt(e/3,10));c.hasClass("under-720")&&(f=parseInt(e/2,10));c.hasClass("under-520")&&(f=parseInt(e,10))}if(c.hasClass("layout-4-cols-15-margin")||c.hasClass("layout-4-cols-10-margin"))e=c.width(),"-1px"==g.css("margin-left")&&(e+=2,g.css("width","calc(100% + 6px)")),"-15px"==g.css("margin-left")&&(e+=30,g.css("width","calc(100% + 34px)")),f=parseInt(e/
    4,10),c.hasClass("under-720")&&(f=parseInt(e/2,10)),c.hasClass("under-520")&&(f=parseInt(e,10));if("cols"==b.settings_mode){if(c.hasClass("layout-2-cols-10-margin")||c.hasClass("layout-2-cols-15-margin"))c.hasClass("under-720")?C(1,a):2!=u&&(2<=k&&(k=0),g.children(".dzs-col").eq(k).append(a),k++,v=2);if(c.hasClass("layout-3-cols-10-margin")||c.hasClass("layout-3-cols-15-margin"))c.hasClass("under-720")?C(2,a):3!=u&&(3<=k&&(k=0),g.children(".dzs-col").eq(k).append(a),k++,v=3);if(c.hasClass("layout-4-cols-10-margin")||
    c.hasClass("layout-4-cols-15-margin"))c.hasClass("under-1000")?c.hasClass("under-520")?C(1,a):c.hasClass("under-720")?C(2,a):C(3,a):4!=u&&(4<=k&&(k=0),g.children(".dzs-col").eq(k).append(a),k++,v=4);if(c.hasClass("layout-5-cols-10-margin")||c.hasClass("layout-5-cols-15-margin"))c.hasClass("under-1000")?c.hasClass("under-720")?C(2,a):C(3,a):5!=u&&(5<=k&&(k=0),g.children(".dzs-col").eq(k).append(a),k++,v=5)}a.css("width","");"on"==b.settings_set_forced_width&&a.outerWidth(f);F&&1>=y&&(1==f%2&&f++,0<
f&&a.outerWidth(f),(a.hasClass("layout-wide")||a.hasClass("layout-big"))&&0==c.hasClass("under-720")&&a.outerWidth(2*f),300>a.width()?a.addClass("under-300"):a.removeClass("under-300"),a.find(".the-feature-con").eq(0).height(y*a.width()),a.hasClass("layout-big")&&0==c.hasClass("under-720")&&a.find(".the-feature-con").eq(0).height(y*a.width()),a.hasClass("layout-tall")&&a.find(".the-feature-con").eq(0).height(2*a.width()+O),a.hasClass("layout-wide")&&0==c.hasClass("under-720")&&a.find(".the-feature-con").eq(0).height(parseInt(.5*
        a.width(),10)-0*O))}),v&&(u=v));e.relayout_isotope&&(e.disable_easing_on_isotope_transiton?(a={},a=d.extend(a,b.settings_isotope_settings),a.transitionDuration="0s",g.isotope(a),setTimeout(function(){},500)):"isotope"==b.settings_mode&&g&&!J&&g.isotope("layout"),setTimeout(function(){"isotope"==b.settings_mode&&g&&!J&&g.isotope("layout")},500));window.dzs_check_lazyloading_images&&window.dzs_check_lazyloading_images()}function da(){Y({parse_items:!1,relayout_isotope:!0,disable_easing_on_isotope_transiton:!1})}
    function C(b,a){var c=Number(a.attr("data-sort"));setTimeout(function(){},c);if(u!=b){k>=b&&(k=0);var c=0,d=1E6;a.css({height:"0px"});for(m=0;m<b;m++)g.children(".dzs-col").eq(m).height()<d&&(d=g.children(".dzs-col").eq(m).height(),c=m);g.children(".dzs-col").eq(c).append(a);k++;a.css({height:""});v=b}}function ea(a){var c=".cat-"+a;a&&a!=b.settings_categories_strall||(c="*");void 0!=w&&(w.children().removeClass("active"),w.children().each(function(){var b=d(this);b.text()==a&&b.addClass("active")}));
        c=("false"===c?!1:c).replace(/ /gi,"-");"isotope"==b.settings_mode&&(b.settings_isotope_settings.filter=c,g.isotope(b.settings_isotope_settings));"simple"==b.settings_mode&&(g.children().fadeOut("fast"),g.children(c).fadeIn("fast"));d(".main-container").get(0)&&d(".main-container").get(0)}function Z(a){function e(){h.css({height:0});var a=100;"wipe"==b.excerpt_con_transition&&(a=100);setTimeout(function(){0<h.find(".advancedscroller").length&&h.find(".advancedscroller").each(function(){var a=d(this);
        if(a.get(0)&&a.get(0).api_force_resize){var b={};a.attr("data-defaultheight")&&(b.calculate_auto_height_default_h=Number(a.attr("data-defaultheight")));a.get(0).api_force_resize(null,b)}});var a=h.children(".dzs-colcontainer").outerHeight();B.hasClass("skin-qcre")?(h.css({height:a}),q.css({height:a}),"zoom"==b.excerpt_con_transition?(q.css({height:a}),h.css({height:a})):(q.css({height:a}),h.css({height:a}),setTimeout(function(){if(d(".scroller-con.type-scrollTop").get(0)&&d(".scroller-con.type-scrollTop").get(0).api_scrolly_to){var a=
        h.offset().top-100;d(".scroller-con.type-scrollTop").get(0).api_scrolly_to(a)}},700))):(h.css({height:h.children(".dzs-colcontainer").outerHeight()+80}),q.css({height:h.children(".dzs-colcontainer").outerHeight()+80}));h.find(".advancedscroller");setTimeout(function(){q.addClass("placed")},500)},a);setTimeout(function(){D(null,{calculate_dims_init:!0,calculate_excerpt_con:!0})},1E3);h.prepend("<style>#"+x+".dzsportfolio .excerpt-content:before{ left:"+(p.offset().left-c.offset().left+p.outerWidth()/
        2-8)+"px; }</style>");p.addClass("active");h.find(".vplayer-tobe.auto-init-from-q").each(function(){var a=d(this);if(window.dzsvp_init){var b={settings_youtube_usecustomskin:"off",init_each:!0,controls_out_opacity:"1",controls_normal_opacity:"1",cueVideo:"off"};window.qcreative_options.video_player_settings&&(b=d.extend(b,window.qcreative_options.video_player_settings));window.dzsvp_init(a,b)}});h.find(".close-btn").bind("click",P);"isotope"==b.settings_mode&&void 0!=d.fn.isotope&&(a=300,"wipe"==
    b.excerpt_con_transition&&(a=101),setTimeout(function(){0<f?q.attr("data-sort",10*f+1):q.attr("data-sort",1E4);g.isotope("insert",q);g.isotope("layout")},a));a=700;"wipe"==b.excerpt_con_transition&&(a=100);setTimeout(function(){h.addClass("placed")},a);setTimeout(function(){d(".main-container").eq(0).get(0)&&d(".main-container").eq(0).get(0).api_toggle_resize&&d(".main-container").eq(0).get(0).api_toggle_resize()},300)}var k=d(this),f=-1;p=null;k.parent().hasClass("zfolio-item")?p=k.parent():k.parent().parent().hasClass("zfolio-item")?
        p=k.parent().parent():k.parent().parent().parent().hasClass("zfolio-item")?p=k.parent().parent().parent():k.parent().parent().parent().parent().hasClass("zfolio-item")&&(p=k.parent().parent().parent().parent());if(null==p)return!1;if(p.hasClass("active"))return P(),!1;if(q)return P(),p.parent().children().removeClass("active"),setTimeout(function(){k.click()},750),!1;var l=p.offset().top,m=!1;for(a=null;0==m;)a=a?a.next():p.next(),a.hasClass("zfolio-item")?a.offset().top!=l&&(m=!0,f=a.parent().children(".isotope-item").index(a)):
        m=!0;for(var l="",m=p.attr("class"),m=m+" ",r=/cat-\w+/gi,t;t=r.exec(m);)t&&(l+=" "+t[0]);B=p.find(".the-content");l='<div class="isotope-item excerpt-content-con'+l+" transition-"+b.excerpt_con_transition+' "><div class="'+B.attr("class")+'" style="">'+B.html()+'<div class="close-btn">x</div></div></div>';0<a.length?a.before(l):g.append(l);q=c.find(".excerpt-content-con").eq(0);h=q.find(".excerpt-content").eq(0);window.dzszfl_execute_target=h;h.find(".toexecute").each(function(){var a=d(this);0==
    a.hasClass("executed")&&(eval(a.text()),a.addClass("executed"))});if(0==h.find(".advancedscroller").length)e();else var u=setInterval(function(){h.find(".advancedscroller").eq(0).hasClass("loaded")&&(e(),clearInterval(u))},100);return!1}function P(){if(q||h){h.removeClass("placed");p.removeClass("active");"wipe"==b.excerpt_con_transition&&(setTimeout(function(){q.css({height:0,"margin-bottom":0});g.isotope("layout")},100),h.animate({height:0},{duration:400,queue:!1}));var a=700;"wipe"==b.excerpt_con_transition&&
    (a=400);setTimeout(function(){"isotope"==b.settings_mode&&void 0!=d.fn.isotope&&g.isotope("remove",q);q&&(q.remove(),q=null);h=p=null;D()},a)}setTimeout(function(){d(".main-container").eq(0).get(0)&&d(".main-container").eq(0).get(0).api_toggle_resize&&d(".main-container").eq(0).get(0).api_toggle_resize()},300)}var c=d(this),x="";c.children();var G,I=c.find(".items").eq(0).children().length,m=0,X,K,g=null,t=null,z=[],J=!1,M=!1,N=0,T=0,u=0,v=0,k=0,y=200,F=!1,O=0,S=!1,q=null,h=null,p=null,B=null,z=[],
        w,A=0,L=null,x=c.attr("id");if("undefined"==typeof x||""==x){for(var Q=0,R="zoomfolio"+Q;0<d("#"+R).length;)Q++,R="zoomfolio"+Q;x=R;c.attr("id",x)}if(!c.hasClass("dzszfl-inited")){c.hasClass("skin-qcre")&&(b.design_skin="skin-qcre");c.hasClass("skin-melbourne")&&(b.design_skin="skin-melbourne");c.hasClass("skin-silver")&&(b.design_skin="skin-silver");c.hasClass("skin-gazelia")&&(b.design_skin="skin-gazelia");g=c.find(".items").eq(0);c.addClass("mode-"+b.settings_mode);if("cols"==b.settings_mode){if(c.hasClass("layout-2-cols-10-margin")||
        c.hasClass("layout-2-cols-15-margin"))for(m=0;2>m;m++)g.append('<div class="dzs-col"></div>');if(c.hasClass("layout-3-cols-10-margin")||c.hasClass("layout-3-cols-15-margin"))for(m=0;3>m;m++)g.append('<div class="dzs-col dzs-col-4"></div>');if(c.hasClass("layout-4-cols-10-margin")||c.hasClass("layout-4-cols-15-margin"))for(m=0;4>m;m++)g.append('<div class="dzs-col "></div>');if(c.hasClass("layout-5-cols-10-margin")||c.hasClass("layout-5-cols-15-margin"))for(m=0;5>m;m++)g.append('<div class="dzs-col dzs-col-1/5"></div>')}0==
    isNaN(Number(b.design_item_thumb_height))&&(y=Number(b.design_item_thumb_height),F=!1,1>=y&&0<y&&(F=!0));0==isNaN(Number(c.attr("data-margin")))&&(O=Number(c.attr("data-margin")));c.addClass("dzszfl-inited");a();r()}return this})};window.dzszfl_init=function(b,a){if("undefined"!=typeof a&&"undefined"!=typeof a.init_each&&1==a.init_each){var l=0,r;for(r in a)l++;1==l&&(a=void 0);d(b).each(function(){d(this).zfolio(a)})}else d(b).zfolio(a)}})(jQuery);
jQuery(document).ready(function(d){dzszfl_init(".zfolio.auto-init",{init_each:!0})});function scrollableElement(d){for(var b=0,a=arguments.length;b<a;b++){var l=arguments[b],r=jQuery(l);if(0<r.scrollTop())return l;r.scrollTop(1);var H=0<r.scrollTop();r.scrollTop(0);if(H)return l}return[]}function get_query_arg(d,b){if(-1<d.indexOf(b+"=")){var a=(new RegExp("[?&]"+b+"=.+")).exec(d);if(null!=a)return a=a[0],-1<a.indexOf("&")&&(a=a.split("&")[1]),a.split("=")[1]}}
function add_query_arg(d,b,a){b=encodeURIComponent(b);a=encodeURIComponent(a);var l=b+"="+a;d=d.replace(new RegExp("(&|\\?)"+b+"=[^&]*"),"$1"+l);var r="";-1<d.indexOf(b+"=")||(r=-1<d.indexOf("?")?"&"+l:"?"+l,d+=r);"NaN"==a&&(d=d.replace(new RegExp("[?|&]"+b+"="+a),""));return d}function is_touch_device(){return!!("ontouchstart"in window)}
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(d,b){window.setTimeout(d,1E3/60)}}();
jQuery.fn.textWidth=function(){var d=jQuery(this),b=d.html();"INPUT"==d[0].nodeName&&(b=d.val());b="<span>"+b+"</span>";jQuery("body").append(b);b=jQuery("span").last();b.css({"font-size":d.css("font-size"),"font-family":d.css("font-family")});d=b.width();b.remove();return d};function can_history_api(){return!(!window.history||!history.pushState)}function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}
function is_android(){return-1<navigator.userAgent.toLowerCase().indexOf("android")}function is_ie(){return-1!=navigator.appVersion.indexOf("MSIE")?!0:!1}function is_firefox(){return-1!=navigator.userAgent.indexOf("Firefox")?!0:!1}function is_opera(){return-1!=navigator.userAgent.indexOf("Opera")?!0:!1}function is_chrome(){return-1<navigator.userAgent.toLowerCase().indexOf("chrome")}function is_safari(){return 0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")}
function version_ie(){return parseFloat(navigator.appVersion.split("MSIE")[1])}function version_firefox(){if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}function version_opera(){if(/Opera[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}function is_ie8(){return is_ie()&&9>version_ie()?!0:!1}function is_ie9(){return is_ie()&&9==version_ie()?!0:!1};